### ISSUE TITLE
Install error reported by user

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/radio_beam#40]
```
$ sudo -H pip install https://github.com/keflavich/radio_beam/archive/master.zip
Collecting https://github.com/keflavich/radio_beam/archive/master.zip
  Downloading https://github.com/keflavich/radio_beam/archive/master.zip (60kB)
    100% |################################| 61kB 370kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-KzpxEp-build/setup.py", line 8, in <module>
        import ah_bootstrap
      File "ah_bootstrap.py", line 921, in <module>
        BOOTSTRAPPER = _Bootstrapper.main()
      File "ah_bootstrap.py", line 217, in main
        bootstrapper.run()
      File "ah_bootstrap.py", line 299, in run
        self.is_submodule = self._check_submodule()
      File "ah_bootstrap.py", line 551, in _check_submodule
        return self._check_submodule_no_git()
      File "ah_bootstrap.py", line 652, in _check_submodule_no_git
        with io.open(gitmodules_path) as f:
    LookupError: unknown encoding:

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-KzpxEp-build
You are using pip version 7.0.3, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

(I think keflavich/master was up to date)

**Comment by keflavich** [comment]
I assume this has been fixed; if a similar issue arises, raise a new issue.
